import os
from dotenv import load_dotenv

load_dotenv()

API_KEY_DB_PATH = os.getenv('API_KEY_DB_PATH')
BASE_URL = os.getenv("BASE_URL")
REALTIME_POSITION = os.getenv("REALTIME_POSITION")
REALTIME_STATIONS_ARRIVAL = os.getenv("REALTIME_STATIONS_ARRIVAL")
REALTIME_STATIONS_ARRIVAL_ALL = os.getenv("REALTIME_STATIONS_ARRIVAL_ALL")